# Generated by Django 4.2 on 2024-12-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(default=1400, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(default=1400, max_length=6),
            preserve_default=False,
        ),
    ]
