# Generated by Django 4.2 on 2024-12-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_booking_date_booking_people_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tablenumber',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
